name: "Tests"

on:
  push:
  schedule:
    # 1st and 15th days of each month at 4:30
    - cron:  '30 4 1,15 * *'
  workflow_dispatch:

jobs:
  terminal_project:
    name: "02_TerminalProject"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout to workspace
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install libncurses-dev

    - name: Compile files using Make
      run: make -C 02_TerminalProject
  
  makefile:
    name: "03_Makefile"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout to workspace
      uses: actions/checkout@v2

    - name: Compile files using Make
      run: make -C 03_Makefile